[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.10" }

[libraries]
idea-ext = { module = "org.jetbrains.gradle.plugin.idea-ext:org.jetbrains.gradle.plugin.idea-ext.gradle.plugin", version = "1.1.10" }
shadow = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version = "8.3.6" }
