package com.zenith

import com.palantir.javapoet.FieldSpec
import com.palantir.javapoet.JavaFile
import com.palantir.javapoet.MethodSpec
import com.palantir.javapoet.TypeSpec
import org.gradle.api.DefaultTask
import org.gradle.api.InvalidUserDataException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import javax.lang.model.SourceVersion
import javax.lang.model.element.Modifier

@CacheableTask
public abstract class GenerateBuildConstants : DefaultTask() {
    @get:Input
    public abstract val packageGroup: Property<String>

    @get:Input
    public abstract val className: Property<String>

    @get:Input
    public abstract val fields: MapProperty<String, String>

    @get:OutputDirectory
    public abstract val outputDirectory: DirectoryProperty

    @TaskAction
    public fun generate() {
        val group = packageGroup.get()
        val className = className.get()
        val fqnClass = "$group.$className"
        val fields = fields.get().toSortedMap()
        val javaFile = if (fields.isEmpty()) {
            null
        } else {
            if (!SourceVersion.isName(fqnClass)) {
                throw InvalidUserDataException("Invalid buildConstants.className or packageGroup: $fqnClass")
            }
            val type = TypeSpec.classBuilder(fqnClass.substringAfterLast('.'))
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
            fields.forEach { (field, value) ->
                if (!SourceVersion.isIdentifier(field) || SourceVersion.isKeyword(field)) {
                    throw InvalidUserDataException("Invalid buildConstants property name: $field")
                }
                type.addField(FieldSpec.builder(String::class.java, field, Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("\$S", value)
                    .build())
            }
            JavaFile.builder(fqnClass.substringBeforeLast('.', ""), type.build())
                .addFileComment("Generated by ZenithProxyDevGradle\n")
                .build()
        }
        val directory = outputDirectory.get().asFile
        if (directory.exists() && !directory.deleteRecursively()) {
            error("Could not clean generated build constants directory: $directory")
        }
        check(directory.mkdirs()) { "Could not create generated build constants directory: $directory" }
        javaFile?.writeTo(directory.toPath())
    }
}
